### ISSUE TITLE
Build failure due to package AsyncWebServer

### ISSUE THREAD

**Issue by orevron** [phobos-/PhobosLT#29]
Trying to build the project (no matter which platform I'm trying to build for wether it is PhobosLT default of S3) I'm getting the same error as the following:

```
Processing ESP32S3 (framework: arduino; platform: espressif32@6.9.0; board: esp32-s3-devkitc-1)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Library Manager: Installing git+https://github.com/mkfrey/AsyncTCP#kconfig_queue_size
git version 2.39.5 (Apple Git-154)
Cloning into '/Users/oevron/.platformio/.cache/tmp/pkg-installing-ftwaudvs'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 23 (delta 0), reused 10 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (23/23), 19.40 KiB | 19.40 MiB/s, done.
Library Manager: AsyncTCP@1.1.1+sha.7855e2c has been installed!
Library Manager: Installing mathieucarbou/ESPAsyncWebServer @ ^3.3.21
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer@3.6.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing mathieucarbou/AsyncTCP @ ^3.3.2
Unpacking  [####################################]  100%
Library Manager: AsyncTCP@3.3.2 has been installed!
Library Manager: Installing bblanchon/ArduinoJson @ 7.2.0
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@7.2.0 has been installed!
Library Manager: Installing ayushsharma82/ElegantOTA @ ^3.1.6
Unpacking  [####################################]  100%
Library Manager: ElegantOTA@3.1.7 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing esp32async/ESPAsyncWebServer @ ^3.7.3
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer@3.7.4 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing ESP32Async/AsyncTCP @ ^3.3.8
Unpacking  [####################################]  100%
Library Manager: AsyncTCP@3.3.8 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PLATFORM: Espressif 32 (6.9.0) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20017.241212+sha.dcc1105b 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ strict
Found 49 compatible libraries
Scanning dependencies...
Dependency Graph
|-- AsyncTCP @ 1.1.1+sha.7855e2c
|-- ESPAsyncWebServer @ 3.6.0
|-- ArduinoJson @ 7.2.0
|-- ElegantOTA @ 3.1.7
|-- DEBUG
|-- LED
|-- WEBSERVER
Building in release mode
Compiling .pio/build/ESP32S3/src/main.cpp.o
Building .pio/build/ESP32S3/bootloader.bin
Generating partitions .pio/build/ESP32S3/partitions.bin
esptool.py v4.5.1
Creating esp32s3 image...
Merged 1 ELF section
Successfully created esp32s3 image.
Compiling .pio/build/ESP32S3/lib44a/AsyncTCP@src-08944e2265d70e4bf415e06a141519af/AsyncTCP.cpp.o
Compiling .pio/build/ESP32S3/lib73a/FS/FS.cpp.o
Compiling .pio/build/ESP32S3/lib73a/FS/vfs_api.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFi.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiAP.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiClient.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiGeneric.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiMulti.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiSTA.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiScan.cpp.o
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiServer.cpp.o
In file included from lib/WEBSERVER/webserver.h:1,
                 from src/main.cpp:3:
.pio/libdeps/ESP32S3/ESPAsyncWebServer/src/ESPAsyncWebServer.h: In member function 'tcp_state AsyncWebServer::state() const':
.pio/libdeps/ESP32S3/ESPAsyncWebServer/src/ESPAsyncWebServer.h:1107:50: error: passing 'const AsyncServer' as 'this' argument discards qualifiers [-fpermissive]
     return static_cast<tcp_state>(_server.status());
                                                  ^
In file included from .pio/libdeps/ESP32S3/ESPAsyncWebServer/src/ESPAsyncWebServer.h:19,
                 from lib/WEBSERVER/webserver.h:1,
                 from src/main.cpp:3:
.pio/libdeps/ESP32S3/AsyncTCP@src-08944e2265d70e4bf415e06a141519af/src/AsyncTCP.h:202:13: note:   in call to 'uint8_t AsyncServer::status()'
     uint8_t status();
             ^~~~~~
Archiving .pio/build/ESP32S3/lib44a/libAsyncTCP@src-08944e2265d70e4bf415e06a141519af.a
Compiling .pio/build/ESP32S3/lib57d/WiFi/WiFiUdp.cpp.o
Archiving .pio/build/ESP32S3/lib73a/libFS.a
*** [.pio/build/ESP32S3/src/main.cpp.o] Error 1
Indexing .pio/build/ESP32S3/lib44a/libAsyncTCP@src-08944e2265d70e4bf415e06a141519af.a
Indexing .pio/build/ESP32S3/lib73a/libFS.a
============================================================================= [FAILED] Took 6.81 seconds =============================================================================

Environment    Status    Duration
-------------  --------  ------------
ESP32S3        FAILED    00:00:06.809
======================================================================== 1 failed, 0 succeeded in 00:00:06.809 ========================================================================
```

Tried to resolve this issue by casting the return value of the `tcp_state` function in the package code, build was successful but then a crash happen in runtime when ever a client is connected to the hotspot.

Can you help me resolve this issue? 

Thanks!

**Comment by DavidJJ** [comment]
I added:

'-fpermissive' to the build flags in targets/PhobosLT.ini

and it built but this error should be fixed.  not sure if it is an issue with PhobosLT or with upstream library

**Comment by mupchu** [comment]
This is still an issue:

Compiling .pio\build\PhobosLT\libfe4\ESPAsyncWebServer\AsyncEventSource.cpp.o
Compiling .pio\build\PhobosLT\libfe4\ESPAsyncWebServer\AsyncJson.cpp.o
*** [.pio\build\PhobosLT\src\main.cpp.o] Error 1
In file included from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncEventSource.h:33,
                 from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncEventSource.cpp:8:
.pio/libdeps/PhobosLT/ESPAsyncWebServer/src/ESPAsyncWebServer.h: In member function 'tcp_state AsyncWebServer::state() const':
.pio/libdeps/PhobosLT/ESPAsyncWebServer/src/ESPAsyncWebServer.h:1107:50: error: passing 'const AsyncServer' as 'this' argument discards qualifiers [-fpermissive]
     return static_cast<tcp_state>(_server.status());
                                                  ^
In file included from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncEventSource.h:10,
                 from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncEventSource.cpp:8:
.pio/libdeps/PhobosLT/AsyncTCP@src-08944e2265d70e4bf415e06a141519af/src/AsyncTCP.h:202:13: note:   in call to 'uint8_t AsyncServer::status()'
     uint8_t status();
             ^~~~~~
*** [.pio\build\PhobosLT\libfe4\ESPAsyncWebServer\AsyncEventSource.cpp.o] Error 1
In file included from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncJson.h:17,
                 from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncJson.cpp:4:
.pio/libdeps/PhobosLT/ESPAsyncWebServer/src/ESPAsyncWebServer.h: In member function 'tcp_state AsyncWebServer::state() const':
.pio/libdeps/PhobosLT/ESPAsyncWebServer/src/ESPAsyncWebServer.h:1107:50: error: passing 'const AsyncServer' as 'this' argument discards qualifiers [-fpermissive]
     return static_cast<tcp_state>(_server.status());
                                                  ^
In file included from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/ESPAsyncWebServer.h:19,
                 from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncJson.h:17,
                 from .pio/libdeps/PhobosLT/ESPAsyncWebServer/src/AsyncJson.cpp:4:
.pio/libdeps/PhobosLT/AsyncTCP@src-08944e2265d70e4bf415e06a141519af/src/AsyncTCP.h:202:13: note:   in call to 'uint8_t AsyncServer::status()'
     uint8_t status();
             ^~~~~~
*** [.pio\build\PhobosLT\libfe4\ESPAsyncWebServer\AsyncJson.cpp.o] Error 1

**Comment by weakwire** [comment]
facing the same issue

**Comment by mupchu** [comment]
so anyone facing this issue, please see the discord to get help.  Answer to this problem can be found there, posting it here as well.

Statl3r — 4/13/2025 10:55 PM
No problem.
You need to adjust the ini-file which corresponds to your build-target - e.g. "PhobosLT.ini" for a original ESP32 (which is integrated in the popular ESP32-WROOM modules). The screenshot shows the modification. You may adapt the line 19 and in addition also line 13.

![Image](https://github.com/user-attachments/assets/7de599cb-ac3b-4920-8681-4f06e5c161dc)

**Comment by weakwire** [comment]
Thanks for that. I already tried and it compiles. however GET /events returns 404 and the implementation doesn't work. Is there a work around to it? I currently use a previous commit 5b580584e4bf9303e3f4fbc1d00f9c77ab5e00c3 that works for me.

**Comment by DavHau** [comment]
Could someone please confirm that this fixes the issue: https://github.com/phobos-/PhobosLT/pull/31

**Comment by spot1984** [comment]
Still failing on ESPAsuncWebServer problems.

I'm new to PhobosLT, working with a fresh clone of the repo.

I did add `-fpermissive` to the build flags of all the targets but there are additional errors related to missing `wl_status_t` type and  `WIFI_OFF` declaration.

Platform IO versions: Core 6.1.19·Home 3.4.4
I do other ESP32 development so my VSCode and PlatformIO installations work.  I did delete the .PlatformIO cache in my user folder and Ardiono15 from %appdata% folder, reinstalled PlatformIO and rebuilt the project from scratch.  Same result.

Please advise.

```
Processing LicardoTimerS3 (framework: arduino; platform: espressif32@6.9.0; board: esp32-s3-devkitc-1)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PLATFORM: Espressif 32 (6.9.0) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)   
PACKAGES:
 - framework-arduinoespressif32 @ 3.20017.241212+sha.dcc1105b
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ strict
Found 49 compatible libraries
Scanning dependencies...
Dependency Graph
|-- AsyncTCP @ 1.1.1+sha.7855e2c
|-- ESPAsyncWebServer @ 3.6.0
|-- ArduinoJson @ 7.2.0
|-- ElegantOTA @ 3.1.7
|-- DEBUG
|-- LED
|-- WEBSERVER
Building in release mode
Compiling .pio\build\LicardoTimerS3\src\main.cpp.o
Archiving .pio\build\LicardoTimerS3\lib39e\libFS.a
Indexing .pio\build\LicardoTimerS3\lib39e\libFS.a
Archiving .pio\build\LicardoTimerS3\libbbf\libWiFi.a
Indexing .pio\build\LicardoTimerS3\libbbf\libWiFi.a
Archiving .pio\build\LicardoTimerS3\lib272\libWebServer.a
Indexing .pio\build\LicardoTimerS3\lib272\libWebServer.a
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\AsyncMessagePack.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\AsyncWebHeader.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\AsyncWebSocket.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\BackPort_SHA1Builder.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\ChunkPrint.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\Middleware.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\WebAuthentication.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\WebHandlers.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\WebRequest.cpp.o
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\WebResponses.cpp.o
In file included from lib/WEBSERVER/webserver.h:1,
                 from src/main.cpp:3:
.pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/ESPAsyncWebServer.h: In member function 'tcp_state AsyncWebServer::state() const':
.pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/ESPAsyncWebServer.h:1479:50: warning: passing 'const AsyncServer' as 'this' argument discards qualifiers [-fpermissive]
     return static_cast<tcp_state>(_server.status());
                                                  ^
In file included from .pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/ESPAsyncWebServer.h:38,
                 from lib/WEBSERVER/webserver.h:1,
                 from src/main.cpp:3:
.pio/libdeps/LicardoTimerS3/AsyncTCP@src-08944e2265d70e4bf415e06a141519af/src/AsyncTCP.h:202:13: note:   in call to 'uint8_t AsyncServer::status()'
     uint8_t status();
             ^~~~~~
Compiling .pio\build\LicardoTimerS3\libba3\ESPAsyncWebServer@3.6.0\WebServer.cpp.o
In file included from src/main.cpp:3:
lib/WEBSERVER/webserver.h: At global scope:
lib/WEBSERVER/webserver.h:27:5: error: 'wl_status_t' does not name a type; did you mean 'ets_status_t'?
     wl_status_t lastStatus = WL_IDLE_STATUS;
     ^~~~~~~~~~~
     ets_status_t
lib/WEBSERVER/webserver.h:26:28: error: 'WIFI_OFF' was not declared in this scope
     wifi_mode_t wifiMode = WIFI_OFF;
                            ^~~~~~~~
lib/WEBSERVER/webserver.h:26:28: note: suggested alternative: 'WIFI_IF_AP'
     wifi_mode_t wifiMode = WIFI_OFF;
                            ^~~~~~~~
                            WIFI_IF_AP
lib/WEBSERVER/webserver.h:28:39: error: 'WIFI_OFF' was not declared in this scope
     volatile wifi_mode_t changeMode = WIFI_OFF;
                                       ^~~~~~~~
lib/WEBSERVER/webserver.h:28:39: note: suggested alternative: 'WIFI_IF_AP'
     volatile wifi_mode_t changeMode = WIFI_OFF;
                                       ^~~~~~~~
                                       WIFI_IF_AP
Compiling .pio\build\LicardoTimerS3\libd1a\ESPAsyncWebServer\AsyncEventSource.cpp.o
*** [.pio\build\LicardoTimerS3\src\main.cpp.o] Error 1
In file included from .pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/AsyncEventSource.h:37,
                 from .pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/AsyncEventSource.cpp:4:
.pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/ESPAsyncWebServer.h: In member function 'tcp_state AsyncWebServer::state() const':
.pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/ESPAsyncWebServer.h:1479:50: warning: passing 'const AsyncServer' as 'this' argument discards qualifiers [-fpermissive]
     return static_cast<tcp_state>(_server.status());
                                                  ^
In file included from .pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/AsyncEventSource.h:9,
                 from .pio/libdeps/LicardoTimerS3/ESPAsyncWebServer/src/AsyncEventSource.cpp:4:
.pio/libdeps/LicardoTimerS3/AsyncTCP@src-08944e2265d70e4bf415e06a141519af/src/AsyncTCP.h:202:13: note:   in call to 'uint8_t AsyncServer::status()'
     uint8_t status();
             ^~~~~~
================================================================================================ [FAILED] Took 9.26 seconds ================================================================================================

Environment     Status    Duration
--------------  --------  ------------
PhobosLT        FAILED    00:00:08.104
ESP32C3         FAILED    00:00:06.947
ESP32S3         FAILED    00:00:08.269
LicardoTimerC3  FAILED    00:00:09.013
LicardoTimerS3  FAILED    00:00:09.263
========================================================================================== 5 failed, 0 succeeded in 00:00:41.596 ========================================================================================== 

```

**Comment by spot1984** [comment]
Fixed!

I pinned the library versions in the target files rather than pinning minimum versions.  I removed the '^' character from the `lib_deps` versions.

e.g. changed:
```
    mathieucarbou/ESPAsyncWebServer @^3.3.21
    bblanchon/ArduinoJson @7.2.0
    ayushsharma82/ElegantOTA @^3.1.6
```
to:
```
    mathieucarbou/ESPAsyncWebServer @3.3.21
    bblanchon/ArduinoJson @7.2.0
    ayushsharma82/ElegantOTA @3.1.6
```

I hope this helps someone.

**Comment by psfales** [comment]
> Thanks for that. I already tried and it compiles. however GET /events returns 404 and the implementation doesn't work. Is there a work around to it? I currently use a previous commit [5b58058](https://github.com/phobos-/PhobosLT/commit/5b580584e4bf9303e3f4fbc1d00f9c77ab5e00c3) that works for me.

I had that result before I realized I needed to "Upload File System Image"
